using DrinkIt.Api.Common;
using DrinkIt.Api.Tenancy;
using DrinkIt.Application.Common;
using DrinkIt.Application.Orders;
using DrinkIt.Domain.Orders;
using Microsoft.AspNetCore.Http.HttpResults;

namespace DrinkIt.Api.Features.Orders;

/// <summary>One drink, as the phone asks for it. What it costs is not in here on purpose.</summary>
public sealed record OrderLineRequestBody(Guid ProductId, int Quantity, string? Note);

/// <summary>
/// An order somebody is confirming from their phone.
/// </summary>
/// <remarks>
/// <see cref="IdempotencyKey"/> is generated by the screen when it opens and
/// sent with every attempt: the signal in a venue is bad, browsers retry, and
/// the same key has to come back with the same order rather than a second one.
/// Criterion 6 of US-11.
/// </remarks>
public sealed record ConfirmOrderRequest(
    string? CustomerName,
    PaymentMethod Method,
    string? IdempotencyKey,
    IReadOnlyList<OrderLineRequestBody>? Lines);

/// <summary>The order as the confirmation screen shows it.</summary>
public sealed record ConfirmedOrderResponse(
    Guid Id,
    string Code,
    string CustomerName,
    decimal Total,
    string Status,
    DateTimeOffset PaidAt);

internal static class OrdersEndpoints
{
    public static IEndpointRouteBuilder MapOrders(this IEndpointRouteBuilder endpoints)
    {
        endpoints
            // The slug is in the path for the same reason as the menu: this is
            // the customer's door, and there is no token to carry a venue.
            .MapPost("/{venueSlug}/orders", ConfirmAsync)
            .AllowAnonymous()
            .WithMetadata(new ScopedBySlugAttribute())
            .WithName("ConfirmOrder")
            .WithTags("Orders")
            .WithSummary("Confirms and pays for an order from the customer's phone.")
            .Produces<ConfirmedOrderResponse>(StatusCodes.Status201Created)
            .ProducesProblem(StatusCodes.Status400BadRequest)
            .ProducesProblem(StatusCodes.Status404NotFound)
            .ProducesProblem(StatusCodes.Status409Conflict);

        return endpoints;
    }

    internal static async Task<IResult> ConfirmAsync(
        string venueSlug,
        ConfirmOrderRequest request,
        CurrentVenue venue,
        ConfirmOrderHandler handler,
        CancellationToken cancellationToken)
    {
        if (venue.Identity is null) return NoSuchVenue(venueSlug);

        Result<ConfirmedOrder> result = await handler.HandleAsync(
            new ConfirmOrderCommand(
                request.CustomerName,
                request.Method,
                request.IdempotencyKey,
                [.. (request.Lines ?? []).Select(line => new OrderLineRequest(line.ProductId, line.Quantity, line.Note))]),
            cancellationToken);

        if (!result.IsSuccess) return Rejected(result.Error!);

        ConfirmedOrder order = result.Value;

        // 201 with the address the order can be read back at, which US-12 will
        // answer. The body is what the confirmation screen draws right now.
        return TypedResults.Created(
            $"/{venueSlug}/orders/{order.Code}",
            new ConfirmedOrderResponse(
                order.Id,
                order.Code,
                order.CustomerName,
                order.Total,
                order.Status.ToString(),
                order.PaidAt));
    }

    /// <summary>
    /// A drink that ran out or left the menu is a conflict, not a bad request:
    /// what the phone sent was right when it was sent, and the answer is that
    /// the world moved. The screen tells them which drink and they try again.
    /// </summary>
    private static readonly Dictionary<string, int> StatusByErrorCode = new(StringComparer.Ordinal)
    {
        [ConfirmOrderHandler.SoldOut.Code] = StatusCodes.Status409Conflict,
        [ConfirmOrderHandler.NotOnTheMenu.Code] = StatusCodes.Status409Conflict,
        [OrderErrors.StockMoved.Code] = StatusCodes.Status409Conflict,
    };

    private static readonly Dictionary<int, string> TitleByStatus = new()
    {
        [StatusCodes.Status400BadRequest] = "Invalid request",
        [StatusCodes.Status409Conflict] = "Conflict",
    };

    private static ProblemHttpResult Rejected(Error error)
    {
        int status = StatusByErrorCode.GetValueOrDefault(error.Code, StatusCodes.Status400BadRequest);

        return TypedResults.Problem(
            title: TitleByStatus.GetValueOrDefault(status, "Invalid request"),
            detail: error.Message,
            statusCode: status,
            type: ProblemTypes.For(error.Code));
    }

    private static ProblemHttpResult NoSuchVenue(string slug) =>
        TypedResults.Problem(
            title: "Not found",
            detail: $"No venue is reached at '{slug}'.",
            statusCode: StatusCodes.Status404NotFound,
            type: ProblemTypes.For("venue.not_found"));
}
